#!/usr/bin/env python3

# TODO
# export API_KEY=u6BdFyg3vQjsovA3Pbp2yYiTp
# export API_SECRET=GV7eeUEGgyLOnjPDkzATIePKrRm9fvVaQHjIAinGQhUx6V6j5W

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @user")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    analyzer = Analyzer(positives, negatives)

    tweets = helpers.get_user_timeline(sys.argv[1], count=50)   # This is going to return a list of 50 strings
    # analyze word
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), end=" ")
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "green"), end=" ")
            print(colored(tweet, "green"))
        else:
            print(colored(score, "yellow"), end=" ")
            print(colored(tweet, "yellow"))


if __name__ == "__main__":
    main()
